version: "3.9"
services:
  api:
    build: .
    container_name: fleet_api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    # volumes:
    #   - ./:/app
  db:
    image: postgres:16-alpine
    container_name: fleet_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:4
    container_name: fleet_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
